### ISSUE TITLE
Data privacy of Slack archive

### ISSUE THREAD

**Issue by Aerosmite** [4350pChris/slack-vuesualizer#761]
Hello, thanks for your great tool! I just have one concern: could anyone access my slack files by "guessing" the token? Wouldn't it more safe to also include a password?

**Comment by 4350pChris** [comment]
In theory yes. However, since there are so many combinations it's practically impossible. There are 122 random bits - i.e. 2^122 possible permutations which is a number greater than the number of atoms in our universe from what I could find.

See https://security.stackexchange.com/a/53477
The UUIDs I'm using fall into the last category listed in the answer.
